export interface InstituteReg { 
    institutionCategory: string,
    name: string,
    instState: string,
    instDistrict: string,
    institutionCode: string,
    email: string,
    diseCode: string,
    location: string,
    institutionType: string,
    affiliatedUnivState: string,
    affiliatedUnivBoard: string,
    startAdmitYear: string,
    setPassword: string,
    confirmPassword: string,
    addressLine1: string,
    addressLine2: string,
    city: string,
    state: string,
    district: string,
    pincode: string,
    principleName: string,
    mobileNumber: string,
    telephone:string
}